### ISSUE TITLE
Missing lanes_pose file

### ISSUE THREAD

**Issue by ShounakCy** [midemig/traj_pred_vae#1]
While running preprocess.py file, its fails due to no lanes_pose.py file.  Do you run that lanes_pose part of the script first?

**Comment by midemig** [comment]
I have temporarily uploaded the lanes.npy file until I can upload the code that generates it

**Comment by ShounakCy** [comment]
Thank you, looking forward to it.

**Comment by midemig** [comment]
The script preprocess.py has been updated and no longer needs lanes.npy
